# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: phpunit/phpunit:5.0.3
clone:
  depth: 1
pipelines:
  default:
    - step:
        script:
          - bash .bitbucket-pipelines/update_composer_repo.sh
  tags:
    "*":
    - step:
        script:
          - bash .bitbucket-pipelines/update_composer_repo.sh
