<?php if (Drip_Connect_Model_Configuration::forCurrentScope()->isEnabled()) : ?>
    <?php $accountId = Drip_Connect_Model_Configuration::forCurrentStoreParam()->getAccountId(); ?>
    <?php if (!empty($accountId)) : ?>
        <!-- Drip -->
        <script type="text/javascript">
            var _dcq = _dcq || [];
            var _dcs = _dcs || {};
            _dcs.account = '<?php echo $accountId?>';

            (function() {
                var dc = document.createElement('script');
                dc.type = 'text/javascript'; dc.async = true;
                dc.src = '//tag.getdrip.com/<?php echo $accountId?>.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(dc, s);
            })();
        </script>
        <!-- end Drip -->

        <?php if (Mage::getSingleton('customer/session')->isLoggedIn()) : ?>
            <?php $customer = Mage::getSingleton('customer/session')->getCustomer(); ?>
            <!-- identify Drip customer -->
            <script type="text/javascript">
            _dcq.push(["identify", {
                email: "<?php echo $customer->getEmail()?>"
            }]);
            </script>
            <!-- end identify -->
        <?php endif; ?>
    <?php else : ?>
        <!-- Skipping Drip JS inclusion due to lack of account id -->
    <?php endif; ?>
<?php endif; ?>
