<?php if (Mage::helper('drip_connect')->isModuleActive()) : ?>
<?php
    $product = Mage::registry('current_product');
    $currentPrice = Mage::helper('drip_connect')->priceAsCents($product->getFinalPrice());
    $initialPrice = Mage::helper('drip_connect')->priceAsCents($product->getPrice());
?>
    <!-- Drip track -->
    <script type="text/javascript">
    _dcq.push(["track", "Viewed a product", {
        product_id: "<?= $product->getId() ?>",
        sku: "<?= $product->getSku() ?>",
        name: "<?= $product->getName() ?>",
        brand: "<?= $product->getAttributeText('manufacturer') ?>",
        categories: "<?= Mage::helper('drip_connect')->getProductCategoryNames($product) ?>",
        price: "<?= $currentPrice ?>",
        <?php if ($currentPrice != $initialPrice) : ?>
        compared_at_price: "<?= $initialPrice ?>",
        <?php endif; ?>
        currency: "<?= Mage::app()->getStore()->getCurrentCurrencyCode() ?>",
        product_url: "<?= $product->getProductUrl() ?>",
        image_url: "<?= Mage::getModel('catalog/product_media_config') ->getMediaUrl($product->getThumbnail()) ?>",
        source: "magento"
    }]);
    </script>
    <!-- end Drip track -->
<?php endif; ?>
