<?php
/**
 * @see Drip_Connect_Block_Adminhtml_System_Config_Sync_Customers
 */
?>
<script type="text/javascript">
//<![CDATA[
    function syncCustomers() {

        var elem = $('<?php echo $this->getHtmlId() ?>');

        params = {
            account_id: '<?=$this->getAccountId()?>',
        };

        new Ajax.Request('<?php echo $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function(response) {
                //TODO
            }
        });
    }
//]]>
</script>
<button onclick="javascript:syncCustomers(); return false;" class="scalable" type="button" id="<?php echo $this->getHtmlId() ?>">
    <span id="sync_result"><?php echo $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>
