<?php
/**
 * @see Drip_Connect_Block_Adminhtml_System_Config_Sync_Orders_Reset
 */
?>
<script type="text/javascript">
//<![CDATA[
    function resetSyncOrdersState() {

        var elem = $('<?php echo $this->getHtmlId()?>');

        elem.addClassName('disabled').setAttribute('disabled', 'disabled');

        params = {
            account_id: '<?php echo $this->getAccountId()?>',
            store_id: '<?php echo $this->getStoreId()?>',
        };

        new Ajax.Request('<?php echo $this->getAjaxUrl()?>', {
            parameters: params,
            onSuccess: function(response) {
                document.location.reload(true);
            },
            onFailure: function() {
                alert('error occured while reseting sync status');
            }
        });
    }
//]]>
</script>
<button onclick="javascript:resetSyncOrdersState(); return false;" type="button" id="<?php echo $this->getHtmlId() ?>" class="scalable delete">
    <?php echo $this->escapeHtml($this->getButtonLabel()) ?>
</button>
